defmodule Worg.Tangle do
  @moduledoc """
  Materialize source blocks tagged `:tangle <path>` into files on disk.

  The `.org` document is the canonical source. Tangled files are derived
  artifacts — overwritten on every tangle. Treat them as build outputs,
  not things to hand-edit.

  Use cases:
    * compose-stage HTML overlays generated by the gamut-director
    * generated CSS / config files produced by an agent
    * scripts the agent wrote that need to live on disk to be executable

  Recognized header forms:

      #+begin_src bash :tangle scripts/run.sh
      #!/usr/bin/env bash
      echo hello
      #+end_src

      #+begin_src css :tangle assets/styles.css :mkdirp yes
      body { background: black; }
      #+end_src

  Path resolution: paths are resolved relative to `base_dir`. Parent
  directories are NOT auto-created — if the destination directory is
  missing the write fails fast (writes happen one at a time; partial
  tangle is fine and the caller can act on the error). When `:mkdirp yes`
  is set on the header, the parent is created with `File.mkdir_p/1`
  before writing.

  Implementation note: regex-based scan of the raw source rather than a
  walk through `Worg.Parser` source-block helpers. This avoids needing
  a new "all source blocks across the document" NIF — every `#+begin_src
  ... :tangle ... #+end_src` line shape is unambiguous in well-formed
  org files.
  """

  @doc """
  Tangle every `:tangle path` block in `src` (a worg source string).
  Paths are resolved relative to `base_dir`.

  Returns `{:ok, [absolute_path]}` listing every file written, in
  source order. `{:error, {:write_failed, path, reason}}` on first
  failure (no rollback of writes that already landed).
  """
  @spec tangle(String.t(), Path.t()) :: {:ok, [Path.t()]} | {:error, term}
  def tangle(src, base_dir) when is_binary(src) do
    case scan_blocks(src) do
      [] ->
        {:ok, []}

      blocks ->
        try do
          written =
            Enum.map(blocks, fn %{path: rel, body: body, mkdirp: mkdirp} ->
              abs = Path.expand(rel, base_dir)

              if mkdirp do
                _ = File.mkdir_p(Path.dirname(abs))
              end

              case Worg.AtomicFile.write(abs, body) do
                :ok -> abs
                {:error, reason} -> throw({:write_failed, abs, reason})
              end
            end)

          {:ok, written}
        catch
          {:write_failed, _, _} = err -> {:error, err}
        end
    end
  end

  # ───── scan: parse :tangle blocks out of raw org source ──────────

  # Returns [%{path: String, body: String, mkdirp: bool}] in source order.
  # Body is the verbatim content between #+begin_src and #+end_src — no
  # leading/trailing whitespace stripped (matches the org-mode tangle
  # convention).
  defp scan_blocks(src) do
    src
    |> String.split("\n")
    |> scan_lines([], nil)
    |> Enum.reverse()
  end

  # State: acc (list of finished blocks, reversed), current (nil OR a
  # map being filled in as we scan the body of an open block).
  defp scan_lines([], acc, _open), do: acc

  defp scan_lines([line | rest], acc, nil) do
    case parse_begin_line(line) do
      {:ok, path, mkdirp} ->
        scan_lines(rest, acc, %{path: path, mkdirp: mkdirp, body_lines: []})

      :no_match ->
        scan_lines(rest, acc, nil)
    end
  end

  defp scan_lines([line | rest], acc, %{body_lines: body_lines} = open) do
    if end_line?(line) do
      block = %{
        path: open.path,
        mkdirp: open.mkdirp,
        body: body_lines |> Enum.reverse() |> Enum.join("\n") |> append_newline()
      }

      scan_lines(rest, [block | acc], nil)
    else
      scan_lines(rest, acc, %{open | body_lines: [line | body_lines]})
    end
  end

  # Match `#+begin_src <lang> ... :tangle <path> ...`. Returns `:no_match`
  # if it's not a begin_src line OR has no :tangle header. Case-insensitive
  # on `#+begin_src` to match org-mode.
  defp parse_begin_line(line) do
    trimmed = String.trim_leading(line)

    case Regex.run(
           ~r/^#\+begin_src\s+\S+\s+(.*)$/i,
           trimmed,
           capture: :all_but_first
         ) do
      [args] ->
        case Regex.run(~r/:tangle\s+(\S+)/, args, capture: :all_but_first) do
          [path] ->
            mkdirp = Regex.match?(~r/:mkdirp\s+yes\b/i, args)
            {:ok, path, mkdirp}

          _ ->
            :no_match
        end

      _ ->
        :no_match
    end
  end

  defp end_line?(line) do
    line
    |> String.trim_leading()
    |> String.match?(~r/^#\+end_src\b/i)
  end

  # Org-mode tangled files conventionally end with a trailing newline.
  defp append_newline(""), do: ""

  defp append_newline(s) do
    if String.ends_with?(s, "\n"), do: s, else: s <> "\n"
  end
end
