defmodule Worg.Tangle do
  @moduledoc """
  Materialize source blocks tagged `:tangle <path>` into files on disk.

  The `.org` document is the canonical source. Tangled files are derived
  artifacts — overwritten on every tangle. Treat them as build outputs, not
  things to hand-edit.

  Use cases at handoff:
    * compose-stage HTML overlays generated by the gamut-director
    * generated CSS / config files produced by an agent
    * scripts the agent wrote that need to live on disk to be executable

  Implementation deferred — wb-4vhr.15.
  """

  @doc """
  Tangle every `:tangle path` block under `src` (a parsed worg document
  string). Paths are resolved relative to `base_dir`.

  Returns `{:ok, [tangled_path]}` listing every file written.
  """
  @spec tangle(String.t(), Path.t()) :: {:ok, [Path.t()]} | {:error, term}
  def tangle(_src, _base_dir), do: raise("not yet implemented — wb-4vhr.15")
end
